spring:
  application:
    name: divinomatheus
  datasource:
    driver-class-name: org.h2.Driver
    username: user
    password: password
    url: jdbc:h2:mem:deliveries-db
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: true