spring:
  application:
    name: divinomatheus
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/deliveries-db